name: Generate Node.js library

on:
  push:
    paths:
      - 'api-client-angular/**'
    branches:
      - main

jobs:
  generate-library:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.16.0'
          npm-sersion: '6.14.11'

      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '14.16.0'
          npm-sersion: '6.14.11'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@daxlto'
      - run: |
          mvn clean install
          cd /home/runner/work/hermes.microservices.libraries.accounting-api/hermes.microservices.libraries.accounting-api/api-client-angular/target/generated-sources/openapi
          npm install typescript@5.5.2 --save-dev --legacy-peer-deps
          npm install --legacy-peer-deps
          npm ci
          npm run build
          npm publish dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

